version: 2.1
description: |
    Secure your code proactively. Use the ZeroThreat AI Powered Web Application/API Security Scanner to perform Dynamic Analysis Security Testing (DAST). It enables comprehensive Dynamic Analysis Security Testing (DAST) to detect vulnerabilities, making findings readily available on the ZeroThreat Portal for review.
display:
    home_url: https://zerothreat.ai/
    source_url: https://github.com/zerothreatai/circleci-orbs
commands:
    scan:
        description: Scan for security issues in web applications/APIs
        parameters:
            ON_PREM_PROXY_API_URL:
                type: string
            WAIT_FOR_ANALYSIS:
                type: boolean
            ZT_TOKEN:
                type: string
        steps:
            - run:
                command: |
                    # Validate ZT_TOKEN is provided
                    if [ -z "<<parameters.ZT_TOKEN>>" ]; then
                      echo "Error: ZT_TOKEN input is required but not provided."
                      exit 1
                    fi

                    # Determine base API endpoint
                    if [ -n "<<parameters.ON_PREM_PROXY_API_URL>>" ]; then
                      BASE_URL="<<parameters.ON_PREM_PROXY_API_URL>>"
                    else
                      BASE_URL="https://api.zerothreat.ai"
                    fi

                    echo "Using API endpoint: $BASE_URL"
                    echo "Starting ZeroThreat AI security scan..."

                    # Initiate the scan
                    response=$(curl -s -X POST "$BASE_URL/api/scan/devops" \
                      -H "Content-Type: application/json" \
                      -d "{\"token\":\"<<parameters.ZT_TOKEN>>\"}")

                    status=$(echo "$response" | jq -r '.status')
                    code=$(echo "$response" | jq -r '.code')
                    message=$(echo "$response" | jq -r '.message')
                    url=$(echo "$response" | jq -r '.url')

                    if [ "$status" != "200" ]; then
                      echo "Failed to initiate scan"
                      echo "Reason: $message"
                      exit 1
                    fi

                    echo "Scan started successfully."
                    echo "Scan Report URL: $url"

                    # Optional: Wait for scan to complete
                    if [ "<<parameters.WAIT_FOR_ANALYSIS>>" == "true" ]; then
                      scanStatus=1
                      while [ "$scanStatus" -lt 4 ]; do
                        sleep 300
                        response=$(curl -s -X GET "$BASE_URL/api/scan/devops/$code")
                        scanStatus=$(echo "$response" | jq -r '.scanStatus')

                        if [ -z "$scanStatus" ] || [ "$scanStatus" = "null" ]; then
                          echo "Scan polling failed: invalid status response."
                          exit 1
                        fi

                        if [ "$scanStatus" -ge 4 ]; then
                          echo "Scan completed successfully."
                          break
                        else
                          echo "Scan still in progress..."
                        fi
                      done
                    fi
                name: ZeroThreat AI Security Scan
executors:
    default:
        description: Default Docker executor
        docker:
            - environment:
                - CIRCLECI: true
              image: cimg/node:20.18
jobs:
    scan-job:
        description: Scan for security issues in web applications/APIs
        docker:
            - image: alpine:latest
        parameters:
            ON_PREM_PROXY_API_URL:
                default: ""
                description: Set proxy url host to scan internal targets.
                type: string
            WAIT_FOR_ANALYSIS:
                default: false
                description: Set this true to wait for analysis to complete before finishing job.
                type: boolean
            ZT_TOKEN:
                description: ZT_TOKEN to authenticate API request & start the scan.
                type: string
        steps:
            - run:
                command: |
                    apk add --no-cache curl jq  # Install curl and jq
                name: Install curl and jq
            - checkout
            - scan:
                ON_PREM_PROXY_API_URL: << parameters.ON_PREM_PROXY_API_URL >>
                WAIT_FOR_ANALYSIS: << parameters.WAIT_FOR_ANALYSIS >>
                ZT_TOKEN: << parameters.ZT_TOKEN >>
examples:
    example:
        description: |
            Example usage of the ZeroThreat AI for vulnerability scanning.
        usage:
            version: "2.1"
            orbs:
                vuln-scan: zerothreat-ai/dast-scanner@0.0.2
            workflows:
                zerothreat-security-scan:
                    jobs:
                        - vuln-scan/scan-job:
                            ZT_TOKEN: AWD4TRX

